### ISSUE TITLE
static -p 1234 display bash: static: command not found

### ISSUE THREAD

**Issue by bitcard** [peterhuba/d-chat#1]
run npm install and npm run build-local both ok. and then run static -p 1234, display bash: static: command not found.

what's wrong with it? how to fix it? thanks.

**Comment by peterhuba** [comment]
`static` here refers to https://www.npmjs.com/package/node-static/v/0.7.10 which is used to serve the directory in which the output will be
You can install it with `npm install -g node-static`

I'll update the readme.

**Comment by bitcard** [comment]
> `static` here refers to https://www.npmjs.com/package/node-static/v/0.7.10 which is used to serve the directory in which the output will be
> You can install it with `npm install -g node-static`
> 
> I'll update the readme.

thanks for your reply. it is ok, this project is so cool!

**Comment by peterhuba** [comment]
By the way I suggest you try to upgrade to latest `js-ipfs` since there have been many performance improvements. Some client code changes would be needed though. I'll see if I'll have the time to upgrade them.
